sudo: false

language: scala

jdk:
   - openjdk8

scala:
   - 2.12.11
   - 2.13.1

#notifications:
#  slack:
#    on_success: never
#    on_failure: always
#    rooms:
#      secure: "STylCrPbSP/R8gAkQ3K+RsSAqGNX3sUeqfF+vIfA5IrQWE44f7yJKVhZ9Dr/TPo+UkNKU9AtB5iCLa2BUpSPuHjexZkfZnjBHO/knv5VociHNq6x+w0FmSDnKnvpbphsAfCiMqEvZ7Dlrccj9xn17DLjIWbMNPOgop3fr9FCWTVvAetxgZ2RaGyhezT4d5CeNc/e3pnNy0Cq/S8TgBPbVsQvDYh7SHdfOPZRZHSQd/Z1cw6e2+EgKdApsTJMm7tqkRvpRehf1nJugWsyRKBfGZPmvygm3V951jcBZ6tsDWfXUaMC/we/0yKdDIRnto8in6fECDz53arMRBgxgNWnllChKBBG7ewW9dxfsqsKNz1ZUgpsRVbSzDbBnebiSA+0nuuWlBNXt52gWxThPBrXtUUNv3ONSjfstLaeHTBPdTO4mBn67ZnhiQ40VhLn906vSl727xyr2qdgueyd+fxbkQZPVehTO9tLl6RvRcjhLi96T08OPzuhPQPrqbAAmHzOJdNxaX2XQNTblBFjaAvU5b8PFkDZOsD+Bj0yFI5bLeG1vL+l8j0dFu8KVF8Xw3oEGrHl1VZFRbhkeyuMtOjTXfnBRkB5cv4NE27VacbNgBDqz6vAP4i9DVy/1DTIQ0T/qn/7hwEOXMa9UMYnbNhOLT+p1KaFUhmxmR9wITdm+xo="


script: sbt --warn ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete